---
deployment:
  tasks:
    - >
      (
        echo "--- Deployment started at $(date) ---" &&
        echo "Changing to repository directory: /home/ay16z7blpox7/trigen-landing-page" &&
        cd /home/ay16z7blpox7/trigen-landing-page &&
        echo "Current directory: $(pwd)" &&
        echo "Installing dependencies..." &&
        /opt/cpanel/ea-nodejs18/bin/npm install &&
        echo "Building application..." &&
        /opt/cpanel/ea-nodejs18/bin/npm run build &&
        echo "Syncing files to public_html..." &&
        /usr/bin/rsync -a --delete /home/ay16z7blpox7/trigen-landing-page/dist/ /home/ay16z7blpox7/public_html/ &&
        echo "--- Deployment finished at $(date) ---"
      ) > /home/ay16z7blpox7/deployment_log.txt 2>&1