---
deployment:
  tasks:
    # This task runs from the root of your repository after a pull.
    # It simply copies the contents of the `dist` folder, which is now
    # part of the repository, to your live public_html directory.
    - /usr/bin/rsync -a --delete dist/ /home/ay16z7blpox7/public_html/ 