---
deployment:
  tasks:
    # Diagnostic step: Find the location of node and npm executables.
    # The output of this will appear in the cPanel deployment log.
    - echo "Searching for node executable..."
    - find /usr /opt /bin /sbin -name "node" -type f 2>/dev/null
    - echo "Searching for npm executable..."
    - find /usr /opt /bin /sbin -name "npm" -type f 2>/dev/null
    - echo "Diagnostic complete." 