---
deployment:
  tasks:
    - echo "Attempting to create a test file..."
    - /bin/touch /home/ay16z7blpox7/cpanel_did_run.txt
    - echo "Test file touched at $(date)" >> /home/ay16z7blpox7/cpanel_did_run.txt
    - echo "Test complete."