---
deployment:
  tasks:
    - export HOME=/home/ay16z7blpox7/
    - echo "--- Starting deployment for trigen-landing-page ---"
    - cd /home/ay16z7blpox7/trigen-landing-page
    - echo "--- In project directory, contents: ---"
    - /bin/ls -A
    - echo "--- Installing dependencies with npm ci ---"
    - /opt/cpanel/ea-nodejs18/bin/npm ci
    - echo "--- Building project with npm run build ---"
    - /opt/cpanel/ea-nodejs18/bin/npm run build
    - echo "--- Syncing built files from dist/ to public_html/ ---"
    - /usr/bin/rsync -a --delete dist/ /home/ay16z7blpox7/public_html/
    - echo "--- Deployment complete ---"