deployment:
  tasks:
    - /bin/echo "*** cPanel read my YAML at $(date) ***"
    - /opt/cpanel/ea-nodejs18/bin/npm ci
    - /opt/cpanel/ea-nodejs18/bin/npm run build
    - /usr/bin/rsync -a --delete dist/ /home/ay16z7blpox7/public_html/